<%@ Page Title="Employees" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Employees.aspx.cs" Inherits="EmployeeManagementSystem.Employees" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .employee-container {
            padding: 20px;
        }
        .page-heading {
            font-size: 32px;
            font-weight: bold;
            color: #111111;
            margin-bottom: 10px;
        }
        .page-description {
            color: #666666;
            margin-bottom: 25px;
        }
        .add-employee-button {
            display: inline-block;
            background-color: #111111;
            color: white;
            padding: 12px 20px;
            border-radius: 5px;
            text-decoration: none;
            margin-bottom: 20px;
        }
        .add-employee-button:hover {
            background-color: #333333;
        }
        .search-container {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
            align-items: center;
        }
        .search-box {
            width: 300px;
            padding: 12px;
            border: 1px solid #cccccc;
            border-radius: 5px;
            font-size: 15px;
            box-sizing: border-box;
        }
        .search-box:focus {
            outline: none;
            border-color: #111111;
        }
        .search-button {
            padding: 12px 20px;
            background-color: #111111;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 15px;
        }
        .search-button:hover {
            background-color: #333333;
        }
        .clear-button {
            padding: 12px 20px;
            background-color: #dddddd;
            color: #111111;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 15px;
        }
        .clear-button:hover {
            background-color: #bbbbbb;
        }
        .employee-card {
            background-color: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.10);
        }
        .employee-grid {
            width: 100%;
            border-collapse: collapse;
        }
        .employee-grid th {
            background-color: #111111;
            color: white;
            padding: 12px;
            text-align: left;
        }
        .employee-grid td {
            padding: 12px;
            border-bottom: 1px solid #dddddd;
        }
        .employee-grid tr:hover {
            background-color: #f5f5f5;
        }
        .employee-grid a {
            color: #111111;
            font-weight: bold;
            text-decoration: none;
            margin-right: 8px;
        }
        .employee-grid a:hover {
            text-decoration: underline;
        }
        .empty-message {
            text-align: center;
            padding: 20px;
            color: #666666;
        }
        @media screen and (max-width: 768px) {
            .search-container {
                flex-direction: column;
                align-items: stretch;
            }
            .search-box {
                width: 100%;
            }
            .search-button,
            .clear-button {
                width: 100%;
            }
            .employee-card {
                overflow-x: auto;
            }
            .employee-grid {
                min-width: 900px;
            }
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="employee-container">
        <h1 class="page-heading">Employee Management</h1>
        <p class="page-description">View and manage employee records.</p>
        <a href="AddEmployee.aspx" class="add-employee-button">+ Add Employee</a>
        <div class="search-container">
            <asp:TextBox ID="txtSearch" runat="server" CssClass="search-box" placeholder="Search employee by name"></asp:TextBox>
            <asp:Button ID="btnSearch" runat="server" Text="Search" CssClass="search-button" OnClick="btnSearch_Click" />
            <asp:Button ID="btnClear" runat="server" Text="Clear" CssClass="clear-button" OnClick="btnClear_Click" />
        </div>
        <div class="employee-card">
            <asp:GridView ID="gvEmployees" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataKeyNames="EmployeeId" OnRowEditing="gvEmployees_RowEditing" OnRowUpdating="gvEmployees_RowUpdating" OnRowCancelingEdit="gvEmployees_RowCancelingEdit" OnRowDeleting="gvEmployees_RowDeleting" CssClass="employee-grid" EmptyDataText="No employees found.">
                <Columns>
                    <asp:BoundField DataField="EmployeeId" HeaderText="ID" ReadOnly="True" />
                    <asp:BoundField DataField="FullName" HeaderText="Full Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="Phone" HeaderText="Phone" />
                    <asp:BoundField DataField="Department" HeaderText="Department" />
                    <asp:BoundField DataField="Designation" HeaderText="Designation" />
                    <asp:BoundField DataField="Salary" HeaderText="Salary" />
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>